### ISSUE TITLE
Guidance needed on required inputs and on interpretation of outputs

### ISSUE THREAD

**Issue by jovanbrusselen** [euraf/agroforestreeadvice#19]
--- It is very nice to see all these tools integrated in one environment. Hopefully all tools referred by Digitaf (youtube channell) would find a place here!
--- comment for all tools: scale and units unclear on the graphic that results after clicking "Compare trees !"; it would benefit all tools if each would have a link to a short manual to help understanding required input and to help interpretation of results.

**Comment by mariegosme** [comment]
Thank you Jo for your feedback! 
--- Regarding your first remark: the objective of AgroforesTreeAdvice is to integrated the tools for tree (and crop) species selection, not all tools in the DigitAF catalog. But for some of the other tools, we are setting up other working groups to do the same kind of integration: we have started working on Financial tools, and we might look at biodiversity tools afterwards. You might also be interested in the carbon tool (https://github.com/euraf/OpenFarmCarbonTracker)
--- Regarding your second remark: thank you for this remark: yes, it was unclear (actually the score is dimensionless because it is a sum of different number of criteria in the different tools => following your remark we simply deleted the axis (will be implemented in the next version). (https://github.com/euraf/agroforestreeadvice/commit/2ea47b4eaf4c428f4889a6bb5f6116fd65a01aff)

**Comment by mariegosme** [comment]
Regarding the need for a manual, we won't write a manual in this repository, which is supposed to be just the crossroads to all the individual tools (which will be referenced in the "databases" page (not yet finished). Hopefully each individual tool will have its own documentation (having a user manual is one of the criteria to obtain a high FAIRness score, which is the overall aim of all DigitAF tools). To read more about the FAIRness score, see this: ... well actually the doc is not yet published online, I asked the developpers to publish it.
